export const dataList = [
    {
        id: 1,
        promotion: "-3%",
        title: "InterContinental Phú Quốc Long Beach Resort",
        location: "Hà Nội",
        price: "2.648.104đ",
        pay: "1.737.098đ",
        linkImg: "https://ak.picdn.net/shutterstock/videos/6899629/thumb/11.jpg",
        point: "9.2",
        cmt:"Tuyệt vời (177 đánh giá)",
        time:"Vừa đặt cách đây 5 giờ trước",
        
    },
    {
        id: 2,
        promotion: "-3%",
        title: "InterContinental Phú Quốc Long Beach Resort",
        location: "Đà Nẵng",
        price: "2.648.104đ",
        pay: "1.737.098đ",
        linkImg: "https://ak.picdn.net/shutterstock/videos/6899629/thumb/11.jpg",
        point: "9.2",
        cmt:"Tuyệt vời (177 đánh giá)",
        time:"Vừa đặt cách đây 5 giờ trước",
        
    },
    {
        id: 3,
        promotion: "-3%",
        title: "InterContinental Phú Quốc Long Beach Resort",
        location: "Hồ Chí Minh",
        price: "2.648.104đ",
        pay: "1.737.098đ",
        linkImg: "https://ak.picdn.net/shutterstock/videos/6899629/thumb/11.jpg",
        point: "9.2",
        cmt:"Tuyệt vời (177 đánh giá)",
        time:"Vừa đặt cách đây 5 giờ trước",
        
    },
    {
        id: 4,
        promotion: "-3%",
        title: "InterContinental Phú Quốc Long Beach Resort",
        location: "Nha Trang",
        price: "2.648.104đ",
        pay: "1.737.098đ",
        linkImg: "https://ak.picdn.net/shutterstock/videos/6899629/thumb/11.jpg",
        point: "9.2",
        cmt:"Tuyệt vời (177 đánh giá)",
        time:"Vừa đặt cách đây 5 giờ trước",
        
    },
    {
        id: 5,
        promotion: "-3%",
        title: "InterContinental Phú Quốc Long Beach Resort",
        location: "Hội An",
        price: "2.648.104đ",
        pay: "1.737.098đ",
        linkImg: "https://ak.picdn.net/shutterstock/videos/6899629/thumb/11.jpg",
        point: "9.2",
        cmt:"Tuyệt vời (177 đánh giá)",
        time:"Vừa đặt cách đây 5 giờ trước",
        
    },
    {
        id: 6,
        promotion: "-3%",
        title: "InterContinental Phú Quốc Long Beach Resort",
        location: "Phú Quốc",
        price: "2.648.104đ",
        pay: "1.737.098đ",
        linkImg: "https://ak.picdn.net/shutterstock/videos/6899629/thumb/11.jpg",
        point: "9.2",
        cmt:"Tuyệt vời (177 đánh giá)",
        time:"Vừa đặt cách đây 5 giờ trước",
        
    },
    {
        id: 7,
        promotion: "-3%",
        title: "InterContinental Phú Quốc Long Beach Resort",
        location: "Đà Lạt",
        price: "2.648.104đ",
        pay: "1.737.098đ",
        linkImg: "https://ak.picdn.net/shutterstock/videos/6899629/thumb/11.jpg",
        point: "9.2",
        cmt:"Tuyệt vời (177 đánh giá)",
        time:"Vừa đặt cách đây 5 giờ trước",
        
    },
    {
        id: 8,
        promotion: "-3%",
        title: "InterContinental Phú Quốc Long Beach Resort",
        location: "Sapa",
        price: "2.648.104đ",
        pay: "1.737.098đ",
        linkImg: "https://ak.picdn.net/shutterstock/videos/6899629/thumb/11.jpg",
        point: "9.2",
        cmt:"Tuyệt vời (177 đánh giá)",
        time:"Vừa đặt cách đây 5 giờ trước",
        
    },
   
]