export const dataBlog = [
  {
    id: 1,
    imgCXG: 'https://uploads.nguoidothi.net.vn/Avatar/l_857ea9c0-e6ce-4614-85b0-e6825eb8b5aa.jpg',
    title: 'Review Tiệm bánh Cối Xay Gió nơi check in hoàn hảo',
    nameDS: 'BY XUÂN HOÀNG',
    time: '10/04/2022',
    amountCmt: '0',
    cmt: 'Điều đầu tiên bạn cảm nhận được khi đến Tiệm bánh Cối Xay Gió này có lẽ là chất retro và ... ',
  },
  {
    id: 2,
    imgCXG: 'https://uploads.nguoidothi.net.vn/Avatar/l_857ea9c0-e6ce-4614-85b0-e6825eb8b5aa.jpg',
    title: 'Review Tiệm bánh Cối Xay Gió nơi check in hoàn hảo',
    nameDS: 'BY XUÂN HOÀNG',
    time: '10/04/2022',
    amountCmt: '0',
    cmt: 'Điều đầu tiên bạn cảm nhận được khi đến Tiệm bánh Cối Xay Gió này có lẽ là chất retro và ... ',
  },
  {
    id: 3,
    imgCXG: 'https://uploads.nguoidothi.net.vn/Avatar/l_857ea9c0-e6ce-4614-85b0-e6825eb8b5aa.jpg',
    title: 'Review Tiệm bánh Cối Xay Gió nơi check in hoàn hảo',
    nameDS: 'BY XUÂN HOÀNG',
    time: '10/04/2022',
    amountCmt: '0',
    cmt: 'Điều đầu tiên bạn cảm nhận được khi đến Tiệm bánh Cối Xay Gió này có lẽ là chất retro và ... ',
  },
  {
    id: 4,
    imgCXG: 'https://uploads.nguoidothi.net.vn/Avatar/l_857ea9c0-e6ce-4614-85b0-e6825eb8b5aa.jpg',
    title: 'Review Tiệm bánh Cối Xay Gió nơi check in hoàn hảo',
    nameDS: 'BY XUÂN HOÀNG',
    time: '10/04/2022',
    amountCmt: '0',
    cmt: 'Điều đầu tiên bạn cảm nhận được khi đến Tiệm bánh Cối Xay Gió này có lẽ là chất retro và ... ',
  },
  {
    id: 5,
    imgCXG: 'https://uploads.nguoidothi.net.vn/Avatar/l_857ea9c0-e6ce-4614-85b0-e6825eb8b5aa.jpg',
    title: 'Review Tiệm bánh Cối Xay Gió nơi check in hoàn hảo',
    nameDS: 'BY XUÂN HOÀNG',
    time: '10/04/2022',
    amountCmt: '0',
    cmt: 'Điều đầu tiên bạn cảm nhận được khi đến Tiệm bánh Cối Xay Gió này có lẽ là chất retro và ... ',
  },
  {
    id: 6,
    imgCXG: 'https://uploads.nguoidothi.net.vn/Avatar/l_857ea9c0-e6ce-4614-85b0-e6825eb8b5aa.jpg',
    title: 'Review Tiệm bánh Cối Xay Gió nơi check in hoàn hảo',
    nameDS: 'BY XUÂN HOÀNG',
    time: '10/04/2022',
    amountCmt: '0',
    cmt: 'Điều đầu tiên bạn cảm nhận được khi đến Tiệm bánh Cối Xay Gió này có lẽ là chất retro và ... ',
  },
  {
    id: 7,
    imgCXG: 'https://uploads.nguoidothi.net.vn/Avatar/l_857ea9c0-e6ce-4614-85b0-e6825eb8b5aa.jpg',
    title: 'Review Tiệm bánh Cối Xay Gió nơi check in hoàn hảo',
    nameDS: 'BY XUÂN HOÀNG',
    time: '10/04/2022',
    amountCmt: '0',
    cmt: 'Điều đầu tiên bạn cảm nhận được khi đến Tiệm bánh Cối Xay Gió này có lẽ là chất retro và ... ',
  },
]