export const dataHotel = [
    {
        id: 1,
        title: "Khách Sạn Ibis Styles Vũng Tàu",
        location: "Thành phố Vũng Tàu",
        price: "1.519.384đ",
        pay: "1.093.007đ",
        linkImg: "https://ak.picdn.net/shutterstock/videos/6899629/thumb/11.jpg",
        point: "9.4",
        cmt:"Tuyệt vời (104 đánh giá)",
        time:"Vừa đặt cách đây 14 giờ",
        bought: "0"
    },
    {
        id: 2,
        title: "Khách Sạn Ibis Styles Vũng Tàu",
        location: "Thành phố Vũng Tàu",
        price: "1.519.384đ",
        pay: "1.093.007đ",
        linkImg: "https://ak.picdn.net/shutterstock/videos/6899629/thumb/11.jpg",
        point: "9.4",
        cmt:"Tuyệt vời (104 đánh giá)",
        time:"Vừa đặt cách đây 14 giờ",
        bought: "0"
    },
    {
        id: 3,
        title: "Khách Sạn Ibis Styles Vũng Tàu",
        location: "Thành phố Vũng Tàu",
        price: "1.519.384đ",
        pay: "1.093.007đ",
        linkImg: "https://ak.picdn.net/shutterstock/videos/6899629/thumb/11.jpg",
        point: "9.4",
        cmt:"Tuyệt vời (104 đánh giá)",
        time:"Vừa đặt cách đây 14 giờ",
        bought: "0"
    },
    {
        id: 4,
        title: "Khách Sạn Ibis Styles Vũng Tàu",
        location: "Thành phố Vũng Tàu",
        price: "1.519.384đ",
        pay: "1.093.007đ",
        linkImg: "https://ak.picdn.net/shutterstock/videos/6899629/thumb/11.jpg",
        point: "9.4",
        cmt:"Tuyệt vời (104 đánh giá)",
        time:"Vừa đặt cách đây 14 giờ",
        bought: "0"
    },
    {
        id: 5,
        title: "Khách Sạn Ibis Styles Vũng Tàu",
        location: "Thành phố Vũng Tàu",
        price: "1.519.384đ",
        pay: "1.093.007đ",
        linkImg: "https://ak.picdn.net/shutterstock/videos/6899629/thumb/11.jpg",
        point: "9.4",
        cmt:"Tuyệt vời (104 đánh giá)",
        time:"Vừa đặt cách đây 14 giờ",
        bought: "0"
    },
    {
        id: 6,
        title: "Khách Sạn Ibis Styles Vũng Tàu",
        location: "Thành phố Vũng Tàu",
        price: "1.519.384đ",
        pay: "1.093.007đ",
        linkImg: "https://ak.picdn.net/shutterstock/videos/6899629/thumb/11.jpg",
        point: "9.4",
        cmt:"Tuyệt vời (104 đánh giá)",
        time:"Vừa đặt cách đây 14 giờ",
        bought: "0"
    },
    {
        id: 7,
        title: "Khách Sạn Ibis Styles Vũng Tàu",
        location: "Thành phố Vũng Tàu",
        price: "1.519.384đ",
        pay: "1.093.007đ",
        linkImg: "https://ak.picdn.net/shutterstock/videos/6899629/thumb/11.jpg",
        point: "9.4",
        cmt:"Tuyệt vời (104 đánh giá)",
        time:"Vừa đặt cách đây 14 giờ",
        bought: "0"
    },
    {
        id: 8,
        title: "Khách Sạn Ibis Styles Vũng Tàu",
        location: "Thành phố Vũng Tàu",
        price: "1.519.384đ",
        pay: "1.093.007đ",
        linkImg: "https://ak.picdn.net/shutterstock/videos/6899629/thumb/11.jpg",
        point: "9.4",
        cmt:"Tuyệt vời (104 đánh giá)",
        time:"Vừa đặt cách đây 14 giờ",
        bought: "0"
    },
]